2024-03-31 09:15:07,267 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Configure stats pid to 3223500
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Loading settings from /home/chenqin.p/.config/wandb/settings
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Loading settings from /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/settings
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_mlora.py', 'program_abspath': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py', 'program': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py'}
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:_log_setup():526] Logging user logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240331_091507-f9jm0vg1/logs/debug.log
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:_log_setup():527] Logging internal logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240331_091507-f9jm0vg1/logs/debug-internal.log
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:init():566] calling init triggers
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:init():616] starting backend
2024-03-31 09:15:07,268 INFO    MainThread:3223500 [wandb_init.py:init():620] setting up manager
2024-03-31 09:15:07,269 INFO    MainThread:3223500 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-31 09:15:07,273 INFO    MainThread:3223500 [wandb_init.py:init():628] backend started and connected
2024-03-31 09:15:07,274 INFO    MainThread:3223500 [wandb_init.py:init():720] updated telemetry
2024-03-31 09:15:07,278 INFO    MainThread:3223500 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-31 09:16:37,296 ERROR   MainThread:3223500 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-31 09:16:39,306 ERROR   MainThread:3223500 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-31 09:16:48,064 WARNING MsgRouterThr:3223500 [router.py:message_loop():77] message_loop has been closed
