2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Configure stats pid to 1570989
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Loading settings from /home/chenqin.p/.config/wandb/settings
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Loading settings from /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/settings
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run_mlora.py', 'program_abspath': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py', 'program': '/cpfs01/user/chenqin.p/dyh/MOELoRA-peft/run_mlora.py'}
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:_log_setup():526] Logging user logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240403_074125-8rr83i6y/logs/debug.log
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:_log_setup():527] Logging internal logs to /cpfs01/user/chenqin.p/dyh/MOELoRA-peft/wandb/run-20240403_074125-8rr83i6y/logs/debug-internal.log
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:init():566] calling init triggers
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:init():616] starting backend
2024-04-03 07:41:25,316 INFO    MainThread:1570989 [wandb_init.py:init():620] setting up manager
2024-04-03 07:41:25,317 INFO    MainThread:1570989 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-03 07:41:25,318 INFO    MainThread:1570989 [wandb_init.py:init():628] backend started and connected
2024-04-03 07:41:25,320 INFO    MainThread:1570989 [wandb_init.py:init():720] updated telemetry
2024-04-03 07:41:25,323 INFO    MainThread:1570989 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-04-03 07:42:55,340 ERROR   MainThread:1570989 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-03 07:42:57,348 ERROR   MainThread:1570989 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/cpfs01/user/chenqin.p/anaconda3/envs/moe/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-03 07:43:10,876 WARNING MsgRouterThr:1570989 [router.py:message_loop():77] message_loop has been closed
